//! plan_ref:
//!   - 14_commands#cli-commands
//!   - 06_backup#backup-command-output-contract
//!
//! Backup command dispatch boundary.

use crate::BackupAction;
use crate::commands;
use std::path::Path;

pub fn run(ledger_dir: &Path, snapshot_depth: usize, action: BackupAction) -> anyhow::Result<()> {
    match action {
        BackupAction::Bind {
            locator,
            repo_id,
            branch_name,
            writer,
            local_writer,
            access,
            dry_run,
        } => commands::backup::bind(
            ledger_dir,
            commands::backup::BindBackupCommandInput {
                locator: &locator,
                repo_id: &repo_id,
                branch_name: &branch_name,
                writer_identity: &writer,
                local_writer_identity: &local_writer,
                access: &access,
                dry_run,
            },
        )?,
        BackupAction::Inspect {
            locator,
            branch,
            credential_ref,
            key_ref,
        } => commands::backup::inspect(
            &locator,
            branch.as_deref(),
            credential_ref.as_deref(),
            key_ref.as_deref(),
        )?,
        BackupAction::List { locator, objects } => commands::backup::list(&locator, &objects)?,
        BackupAction::Verify {
            locator,
            branch,
            objects,
            expected_packs,
        } => commands::backup::verify(&locator, &branch, &objects, &expected_packs)?,
        BackupAction::Run {
            locator,
            repo_id,
            branch_name,
            writer,
            local_writer,
            credential_ref,
            key_ref,
            pack_sequence,
            ledger_start,
            ledger_end,
            ledger_event_count,
            snapshot_count,
            payload_digest,
            artifact,
            encrypted,
            authenticated,
            dry_run,
        } => commands::backup::run_backup(commands::backup::RunBackupCommandInput {
            locator: &locator,
            repo_id: &repo_id,
            branch_name: &branch_name,
            writer_identity: &writer,
            local_writer_identity: &local_writer,
            credential_ref: &credential_ref,
            key_ref: &key_ref,
            pack_sequence,
            ledger_start,
            ledger_end,
            ledger_event_count,
            snapshot_count,
            payload_digest: &payload_digest,
            artifact_path: artifact.as_deref(),
            encrypted,
            authenticated,
            dry_run,
        })?,
        BackupAction::Restore {
            locator,
            repo_id,
            manifest_repo_id,
            branch,
            manifest_digest,
            pack_digests,
            credential_ref,
            key_ref,
            pack_sequence,
            ledger_start,
            ledger_end,
            ledger_event_count,
            snapshot_count,
            mode,
            write_gate,
            manifest_verified,
            packs_downloaded,
            packs_decrypted,
            dry_run,
        } => commands::backup::restore(
            ledger_dir,
            snapshot_depth,
            commands::backup::RestoreCommandInput {
                locator: &locator,
                repo_id: &repo_id,
                manifest_repo_id: &manifest_repo_id,
                branch: &branch,
                manifest_digest: &manifest_digest,
                pack_digests: &pack_digests,
                credential_ref: credential_ref.as_deref(),
                key_ref: key_ref.as_deref(),
                pack_sequence,
                ledger_start,
                ledger_end,
                ledger_event_count,
                snapshot_count,
                mode: &mode,
                write_gate,
                manifest_verified,
                packs_downloaded,
                packs_decrypted,
                dry_run,
            },
        )?,
        BackupAction::Unbind {
            locator,
            repo_id,
            branch_name,
            writer,
            local_writer,
            access,
            dry_run,
        } => commands::backup::unbind(
            ledger_dir,
            commands::backup::UnbindBackupCommandInput {
                locator: &locator,
                repo_id: &repo_id,
                branch_name: &branch_name,
                writer_identity: &writer,
                local_writer_identity: &local_writer,
                access: &access,
                dry_run,
            },
        )?,
    }
    Ok(())
}
