[package]
name = "deve_mobile"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
native-packaging = ["dep:tauri", "dep:tauri-build", "tauri/wry"]

[dependencies]
deve_core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tauri = { version = "2.11.1", optional = true, default-features = false, features = [] }

[build-dependencies]
tauri-build = { version = "2.6.1", optional = true, default-features = false, features = [] }
