//! Deterministic human-readable projection of the acceptance matrix.
//! plan_ref: 18_release#first-tag-acceptance-matrix

use super::model::{MATRIX_PATH, MatrixRow, RENDERED_PATH};
use anyhow::{Context, Result, bail};
use std::fs;
use std::path::Path;

pub(super) fn render(rows: &[MatrixRow]) -> String {
    let mut output = String::from(
        "<!-- Generated by `deve_baseline acceptance-matrix --render`; do not edit. -->\n\n\
         # Acceptance Matrix\n\n\
         Authority: [`docs/registry/acceptance-matrix.tsv`](registry/acceptance-matrix.tsv).\n\n\
         | Requirement | Journey | Flow | Case | Surface / mode | Gate | Requirement | Evidence | Evidence ref | Freshness | Note |\n\
         |---|---|---|---|---|---|---|---|---|---|---|\n",
    );
    for row in rows {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` / `{}` | `{}` | `{}` | `{}` (`{}`) | `{}` | `{}` | {} |\n",
            escape(&row.requirement_id),
            escape(&row.journey_id),
            escape(&row.flow_id),
            escape(&row.case_id),
            escape(&row.surface),
            escape(&row.mode),
            escape(&row.gate),
            escape(&row.requirement),
            escape(&row.evidence_id),
            escape(&row.evidence_kind),
            escape(&row.evidence_ref),
            escape(&row.freshness),
            escape(&row.note),
        ));
    }
    output
}

pub(super) fn check_drift(root: &Path, rows: &[MatrixRow]) -> Result<()> {
    let expected = render(rows);
    let actual = fs::read_to_string(root.join(RENDERED_PATH))
        .with_context(|| format!("acceptance-matrix: missing generated {RENDERED_PATH}"))?;
    if actual == expected {
        Ok(())
    } else {
        bail!(
            "acceptance-matrix: {RENDERED_PATH} drifted from {MATRIX_PATH}; run `cargo run -p deve_baseline -- acceptance-matrix --render`"
        )
    }
}

pub(super) fn write(root: &Path, rows: &[MatrixRow]) -> Result<()> {
    fs::write(root.join(RENDERED_PATH), render(rows))
        .with_context(|| format!("acceptance-matrix: failed to write {RENDERED_PATH}"))
}

fn escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}
