#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# SET-007: server-backed Settings API remains a future boundary; current
# settings mutation is config.toml-only.

fail() {
  echo "cli-settings-baseline-check: $*" >&2
  exit 1
}

check_contains() {
  local file="$1"
  local pattern="$2"
  rg -q --fixed-strings "$pattern" "$ROOT_DIR/$file" \
    || fail "missing '$pattern' in $file"
}

check_absent() {
  local file="$1"
  local pattern="$2"
  if rg -q --fixed-strings "$pattern" "$ROOT_DIR/$file"; then
    fail "unexpected '$pattern' in $file"
  fi
}

# CLI command surface.
check_contains apps/cli/src/main.rs "Init {"
check_contains apps/cli/src/main.rs "Scan,"
check_contains apps/cli/src/main.rs "Watch {"
check_contains apps/cli/src/main.rs "Serve {"
check_contains apps/cli/src/main.rs "Dump {"
check_contains apps/cli/src/main.rs "Export {"
check_contains apps/cli/src/main.rs "Graph {"
check_contains apps/cli/src/main.rs "VerifyP2P"
check_contains apps/cli/src/main.rs "Seed {"
check_contains apps/cli/src/main.rs "NodeCheck {"
check_contains apps/cli/src/main.rs "Recover {"
check_contains apps/cli/src/main.rs "Repair {"
check_contains apps/cli/src/main.rs "ScStatus {"
check_contains apps/cli/src/main.rs "Git {"
check_contains apps/cli/src/main.rs "Config {"
check_contains apps/cli/src/dispatch.rs "ConfigAction::Print => commands::config::print(config)?"
check_contains apps/cli/src/dispatch.rs "ConfigAction::Set { key, value } => commands::config::set(&key, &value)?"
check_contains apps/cli/src/dispatch.rs "Commands::Graph"
check_contains apps/cli/src/dispatch.rs "Commands::VerifyP2P"
check_contains apps/cli/src/dispatch.rs "Commands::Seed"
check_contains apps/cli/src/dispatch.rs "Commands::NodeCheck"
check_contains apps/cli/src/dispatch.rs "Commands::ScStatus"
check_contains apps/cli/src/dispatch.rs "Commands::Git"
check_contains apps/cli/src/dispatch.rs "GitAction::Status"
check_contains apps/cli/src/dispatch.rs "GitAction::Mirror"
check_contains apps/cli/src/dispatch.rs "GitAction::Export"
check_contains apps/cli/src/dispatch.rs "GitAction::Import"
check_contains apps/cli/src/dispatch.rs "GitAction::Push"
check_contains docs/acceptance-cases/11_commands_settings.md "case_id: CMD-007A"
check_contains docs/acceptance-cases/11_commands_settings.md "case_id: CMD-007B"
check_contains scripts/smoke-web-release-build.sh "CMD-007A Web release build smoke."
check_absent scripts/smoke-web-release-build.sh "REL-004 Web release build smoke."
check_contains docs/acceptance-cases/11_commands_settings.md "deve graph --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve sc-status --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve git status --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve git mirror --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve git export --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve git import --help"
check_contains docs/acceptance-cases/11_commands_settings.md "deve git push --help"
check_contains apps/cli/src/commands/watch.rs "install_shutdown_handler()?"
check_contains apps/cli/src/commands/watch.rs "Failed to set Ctrl-C handler"
check_absent apps/cli/src/commands/watch.rs "无法设置 Ctrl+C 处理器"

# config.toml remains the current authoritative runtime settings file.
check_contains apps/cli/src/commands/config.rs "const CONFIG_FILE: &str = \"config.toml\";"
check_contains apps/cli/src/commands/config.rs "mod tests;"
check_contains apps/cli/src/commands/config.rs "toml::to_string_pretty(config)"
check_contains apps/cli/src/commands/config.rs "parse_whitelisted_value"
check_contains apps/cli/src/commands/config/tests.rs "supported_config_keys_match_settings_plan_tables"
check_contains apps/cli/src/commands/config/tests.rs "supported_config_schema_matches_settings_plan_type_and_choices"
check_contains apps/cli/src/commands/init.rs "init_config_template_matches_current_settings_schema"
check_contains apps/cli/src/commands/init.rs "[ai.agent_bridge]"
check_contains apps/cli/src/commands/config/schema.rs "\"ui.sidebar_width\""
check_contains apps/cli/src/commands/config/schema.rs "\"ai.mode\""
check_contains apps/cli/src/commands/config.rs "Updated config.toml is not compatible with runtime config"
check_contains crates/core/src/config/tests.rs "mod agent_bridge_tests;"
check_contains crates/core/src/config/tests.rs "mod load_tests;"
check_contains crates/core/src/config/tests/agent_bridge_tests.rs "trusted_cli_requested_mode_is_preserved_when_agent_cli_path_is_missing"
check_contains crates/core/src/config/tests/agent_bridge_tests.rs "trusted_cli_requested_mode_is_preserved_when_agent_cli_path_is_relative"
check_contains crates/core/src/config/tests/agent_bridge_tests.rs "trusted_cli_requested_mode_is_preserved_when_agent_cli_path_is_not_executable"
check_contains crates/core/src/config/tests/agent_bridge_tests.rs "trusted_cli_mode_is_kept_when_policy_conditions_are_satisfied"
check_contains crates/core/src/config/tests/agent_bridge_tests.rs "trusted_cli_mode_honors_agent_bridge_env_aliases"
check_contains crates/core/src/config/tests/load_tests.rs "load_checked_fails_closed_on_invalid_agent_bridge_alias_bool"
check_contains crates/core/src/config/tests/load_tests.rs "load_checked_fails_closed_on_invalid_runtime_enum_value"
check_contains crates/core/src/config/tests/load_tests.rs "runtime_config_value_parsers_reject_unknown_values"
check_absent apps/cli/src/server/agent_bridge/policy.rs "DEVE_AI_AGENT_BRIDGE_ENABLED"
check_absent apps/cli/src/server/agent_bridge/policy.rs "DEVE_AI_AGENT_BRIDGE_TRUSTED"
check_contains docs/plan/13_settings.md "DEVE_AI_AGENT_BRIDGE_ENABLED"
check_contains docs/plan/13_settings.md "DEVE_AI_AGENT_BRIDGE_TRUSTED"
check_contains docs/plan/13_settings.md '运行模式预设: `standard` (默认), `low-spec` (低配).'
check_absent docs/plan/13_settings.md '`debug` (调试)'
check_contains docs/plan/13_settings.md "**Future Settings Surface**"
check_contains docs/plan/13_settings.md "server-backed Settings API、独立设置文件或统一 GUI 持久化 **MAY** 另行设计"
check_contains docs/plan/13_settings.md "启用前 **MUST** 更新本章、feature spec 与 acceptance case"
check_absent apps/cli/src/server/router.rs "/api/settings"

# UI command surfaces remain reachable through the shortcut layer.
check_contains apps/web/src/shortcuts/global.rs "Ctrl+P"
check_contains apps/web/src/shortcuts/global.rs "Ctrl+Shift+P"
check_contains apps/web/src/shortcuts/global.rs "Ctrl+Shift+K"
check_contains apps/web/src/shortcuts/global.rs "Ctrl+L"
check_contains apps/web/src/shortcuts/global.rs "Ctrl+Shift+O"
check_contains apps/web/src/shortcuts/global.rs "Ctrl+B"
check_contains apps/web/src/shortcuts/global/handlers.rs "GlobalShortcutAction::BranchSwitcher"
check_contains apps/web/src/shortcuts/global/handlers.rs "toggle_search_mode(signals, \"@\");"
check_contains apps/web/src/shortcuts/global/handlers.rs "GlobalShortcutAction::ToggleLanguage"
check_contains apps/web/src/shortcuts/global/handlers.rs "GlobalShortcutAction::ToggleOutline"
check_contains apps/web/src/shortcuts/global/handlers.rs "GlobalShortcutAction::ToggleSidebar"
check_contains apps/web/src/components/command_palette/mod.rs "CommandPalette"
check_contains apps/web/src/components/command_palette/registry.rs "\"toggle_sidebar\""
check_contains apps/web/src/components/command_palette/registry.rs "static_commands_include_sidebar_toggle_when_control_is_available"
check_contains apps/web/src/components/command_palette/registry/reserved.rs "source_control_reserved_commands"
check_contains apps/web/src/components/command_palette/registry/reserved.rs "ai_reserved_commands"
check_contains apps/web/src/components/command_palette/registry.rs "static_commands_partition_reserved_surfaces"
check_contains apps/web/src/i18n/command_palette.rs "Source Control: Commit"
check_contains apps/web/src/i18n/command_palette.rs "AI: Switch to BUILD Mode"
check_contains docs/acceptance-cases/11_commands_settings.md "case_id: CMD-004C"
check_contains docs/acceptance-cases/11_commands_settings.md "case_id: CMD-004D"
check_contains docs/acceptance-cases/11_commands_settings.md "cargo test -p deve_web reserved_commands -- --nocapture"
check_contains docs/acceptance-cases/11_commands_settings.md "cargo test -p deve_web global_shortcut -- --nocapture"
check_contains apps/web/src/components/branch_switcher/mod.rs "BranchSwitcher"
check_contains apps/web/src/i18n/sidebar.rs "Switch Branch (Ctrl+Shift+K)"
check_contains apps/web/src/components/settings.rs "current_boundary_desc"
check_contains apps/web/src/components/settings.rs "language_button_state"
check_contains apps/web/src/components/settings.rs "reserved_setting_state"
check_contains apps/web/src/components/settings.rs "data-deve-setting-disabled"
check_contains apps/web/src/components/settings.rs "aria-disabled"
check_contains apps/web/src/i18n/settings.rs "deve config set"
check_contains apps/web/src/i18n/settings.rs "config.toml"
check_contains apps/web/src/i18n/settings.rs "Future setting: not available in the current release"
check_contains apps/web/src/i18n/settings.rs "reserved_setting_copy_marks_future_boundary"
check_absent apps/web/src/i18n/settings.rs "Coming in Phase 6"
check_contains apps/web/src/components/settings_sections_policy/tests.rs "language_buttons_reflect_current_locale"
check_contains apps/web/src/components/settings_sections_policy/tests.rs "reserved_setting_state_exposes_disabled_reason"
check_absent apps/web/src/components/settings_sections_policy.rs "pointer-events-none grayscale"
check_contains apps/web/src/components/settings_sections.rs "sync_mode_button_state"
check_contains apps/web/src/components/settings_sections_policy/tests.rs "sync_mode_buttons_reflect_current_mode"
check_contains apps/web/src/components/settings_sections_policy/tests.rs "sync_mode_buttons_treat_unknown_mode_as_auto_safe_default"
check_contains docs/acceptance-cases/15_settings_operation_refs.md "reserved_setting_has_marker"
check_contains docs/acceptance-cases/15_settings_operation_refs.md "reserved_setting_has_aria_disabled true"
check_contains docs/acceptance-cases/15_settings_operation_refs.md "cargo test -p deve_web settings -- --nocapture"
check_contains docs/features/operations/settings_feedback_render.md "aria-disabled"
check_contains docs/features/operations/settings_runtime_feedback.md "aria-disabled"

echo "cli-settings-baseline-check: ok"
