#!/usr/bin/env bash
set -euo pipefail

# REL-005/REL-006/REL-007/REL-008/REL-009/REL-010/REL-011 keep Docker, compose, release workflow,
# shell-only platform evidence, runtime visibility, and smoke surfaces aligned
# with the current release baseline.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  echo "release-baseline-check: $*" >&2
  exit 1
}

contains() {
  local file="$1"
  local text="$2"
  MSYS2_ARG_CONV_EXCL="$text" rg --fixed-strings --quiet -- "$text" "$ROOT_DIR/$file" \
    || fail "missing '$text' in $file"
}

not_contains() {
  local file="$1"
  local text="$2"
  if MSYS2_ARG_CONV_EXCL="$text" rg --fixed-strings --quiet -- "$text" "$ROOT_DIR/$file"; then
    fail "unexpected '$text' in $file"
  fi
}

line_no() {
  local file="$1"
  local text="$2"
  MSYS2_ARG_CONV_EXCL="$text" rg --line-number --fixed-strings -- "$text" "$ROOT_DIR/$file" | head -n1 | cut -d: -f1
}

assert_before() {
  local file="$1"
  local before="$2"
  local after="$3"
  local before_line
  local after_line
  before_line="$(line_no "$file" "$before")"
  after_line="$(line_no "$file" "$after")"
  [[ -n "$before_line" ]] || fail "missing '$before' in $file"
  [[ -n "$after_line" ]] || fail "missing '$after' in $file"
  (( before_line < after_line )) || fail "'$before' must appear before '$after' in $file"
}

git -c safe.directory="$ROOT_DIR" -C "$ROOT_DIR" ls-files --error-unmatch Cargo.lock >/dev/null 2>&1 \
  || fail "Cargo.lock must be tracked for locked release/Docker builds"
if git -c safe.directory="$ROOT_DIR" -C "$ROOT_DIR" check-ignore -q Cargo.lock; then
  fail "Cargo.lock must not be ignored"
fi

contains ".github/workflows/release.yml" "tags: ['v*']"
contains ".github/workflows/release.yml" "cargo clippy --locked --all-targets -- -D warnings"
contains ".github/workflows/release.yml" "actions/checkout@v6"
contains ".github/workflows/release.yml" "actions/setup-node@v6"
contains ".github/workflows/release.yml" "node-version: 24"
contains ".github/workflows/release.yml" "cargo check --locked -p deve_web --target wasm32-unknown-unknown"
contains ".github/workflows/release.yml" "cargo install cargo-audit --locked"
contains ".github/workflows/release.yml" "DEVE_RELEASE_AUDIT_REQUIRED=1 scripts/check-release-audit-gate.sh"
contains ".github/workflows/release.yml" "scripts/plan-coverage.sh --write-report"
contains ".github/workflows/release.yml" "scripts/check-architecture-registry.sh"
contains ".github/workflows/release.yml" "scripts/check-native-track-boundary.sh"
contains ".github/workflows/release.yml" "scripts/check-native-packaging-gate.sh"
contains ".github/workflows/release.yml" "scripts/check-native-process-adapter-gate.sh"
contains ".github/workflows/release.yml" "scripts/check-mobile-platform-package-preflight.sh"
contains ".github/workflows/release.yml" "scripts/check-mobile-android-shell-package-build.sh"
contains ".github/workflows/release.yml" "scripts/check-desktop-signing-preflight.sh"
contains ".github/workflows/release.yml" "scripts/check-mobile-android-release-preflight.sh"
contains ".github/workflows/release.yml" "scripts/check-graph-baseline.sh"
contains ".github/workflows/release.yml" "cargo test --locked"
contains ".github/workflows/release.yml" "docker/build-push-action@v6"
contains ".github/workflows/release.yml" "platforms: linux/amd64"
contains ".github/workflows/release.yml" "type=raw,value=latest"
contains ".github/workflows/docker-smoke.yml" "workflow_dispatch:"
contains ".github/workflows/docker-smoke.yml" "actions/checkout@v6"
contains ".github/workflows/docker-smoke.yml" "docker version"
contains ".github/workflows/docker-smoke.yml" "DEVE_DOCKER_SMOKE_REQUIRED: \"1\""
contains ".github/workflows/docker-smoke.yml" "DEVE_DOCKER_SMOKE_IMAGE: deve-notebook:ci-smoke-\${{ github.run_id }}"
contains ".github/workflows/docker-smoke.yml" "scripts/smoke-docker-release.sh"
contains ".github/workflows/native-target-host.yml" "workflow_dispatch:"
contains ".github/workflows/native-target-host.yml" "target:"
contains ".github/workflows/native-target-host.yml" "required_preflight:"
contains ".github/workflows/native-target-host.yml" "run_desktop_package_build:"
contains ".github/workflows/native-target-host.yml" "run_desktop_startup_smoke:"
contains ".github/workflows/native-target-host.yml" "run_desktop_installer_smoke:"
contains ".github/workflows/native-target-host.yml" "run_mobile_android_package_build:"
contains ".github/workflows/native-target-host.yml" "run_mobile_android_install_startup_smoke:"
contains ".github/workflows/native-target-host.yml" "run_mobile_ios_package_build:"
contains ".github/workflows/native-target-host.yml" "run_mobile_ios_install_startup_smoke:"
contains ".github/workflows/native-target-host.yml" "aarch64-apple-ios-sim"
contains ".github/workflows/native-target-host.yml" "x86_64-linux-android"
contains ".github/workflows/native-target-host.yml" "actions/setup-java@v5"
contains ".github/workflows/native-target-host.yml" "Install Android SDK platform tools"
contains ".github/workflows/native-target-host.yml" "sdkmanager \"platform-tools\" \"emulator\""
contains ".github/workflows/native-target-host.yml" "runs-on: macos-latest"
contains ".github/workflows/native-target-host.yml" "runs-on: windows-latest"
contains ".github/workflows/native-target-host.yml" "runs-on: ubuntu-latest"
contains ".github/workflows/native-target-host.yml" "scripts/build-web-dist-ci.sh"
contains ".github/workflows/native-target-host.yml" "scripts/install-native-target-host-tools.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-desktop-target-host-preflight.sh"
contains ".github/workflows/native-target-host.yml" "DEVE_DESKTOP_PACKAGE_NO_SIGN: \"1\""
contains ".github/workflows/native-target-host.yml" "Install Windows installer tools"
contains ".github/workflows/native-target-host.yml" "choco install nsis -y --no-progress"
contains ".github/workflows/native-target-host.yml" "scripts/check-desktop-platform-package-build.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-desktop-package-startup-smoke.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-desktop-native-session-package-smoke.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-desktop-installer-smoke.sh"
contains ".github/workflows/native-target-host.yml" "Reject Desktop macOS installer smoke without package build"
contains ".github/workflows/native-target-host.yml" "Reject Desktop Windows installer smoke without package build"
contains ".github/workflows/native-target-host.yml" "invalid_installer_request="
contains ".github/workflows/native-target-host.yml" "scripts/check-mobile-platform-package-preflight.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-mobile-android-shell-package-build.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-mobile-android-emulator-install-startup-smoke.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-mobile-ios-shell-package-build.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-mobile-ios-install-startup-smoke.sh"
contains ".github/workflows/native-target-host.yml" "scripts/check-native-process-adapter-gate.sh"
contains ".github/workflows/native-target-host.yml" "DEVE_NATIVE_PROCESS_ADAPTER_RUN_DESKTOP_NATIVE_PACKAGING_TESTS: \"0\""
contains ".github/workflows/native-target-host.yml" "actions/checkout@v6"
contains ".github/workflows/native-target-host.yml" "actions/setup-node@v6"
contains ".github/workflows/native-target-host.yml" "node-version: 24"
contains ".github/workflows/native-target-host.yml" "actions/upload-artifact@v7"
contains ".github/workflows/native-target-host.yml" "target/release/bundle/**"
contains ".github/workflows/native-target-host.yml" "scripts/write-native-target-host-evidence.sh"
contains ".github/workflows/native-target-host.yml" "deve-native-target-host-evidence-macos"
contains ".github/workflows/native-target-host.yml" "deve-native-target-host-evidence-windows"
contains ".github/workflows/native-target-host.yml" "deve-native-target-host-evidence-android"
contains ".github/workflows/native-target-host.yml" "target/mobile-android-emulator-smoke/**"
contains ".github/workflows/native-target-host.yml" "deve-native-target-host-evidence-ios"
contains ".github/workflows/native-target-host.yml" "deve-mobile-android-packages"
contains ".github/workflows/native-target-host.yml" "iOS package build remains closed because run_mobile_ios_package_build=false"
contains ".github/workflows/native-target-host.yml" "deve-mobile-ios-packages"
contains ".github/workflows/native-target-host.yml" "DEVE_MOBILE_ANDROID_PACKAGE_TARGET=x86_64"
contains ".github/workflows/native-target-host.yml" "DEVE_MOBILE_ANDROID_ADB_TIMEOUT_SECS=120"
contains ".github/workflows/native-target-host.yml" "DEVE_MOBILE_PACKAGE_HOST_NATIVE_PACKAGING_CHECK: \"0\""
contains ".github/workflows/native-target-host.yml" "DEVE_MOBILE_IOS_PACKAGE_TARGET: aarch64-sim"
contains ".github/workflows/native-target-host.yml" "DEVE_MOBILE_IOS_BOOT_SIMULATOR: \"1\""
contains ".github/AGENTS.md" "optional target-host workflows"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_DISPATCH"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_DESKTOP_STARTUP_SMOKE"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_DESKTOP_INSTALLER_SMOKE"
contains "scripts/dispatch-native-target-host-workflow.sh" "desktop installer smoke requires DEVE_NATIVE_TARGET_HOST_RUN_DESKTOP_PACKAGE_BUILD=true"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_MOBILE_ANDROID_PACKAGE_BUILD"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_MOBILE_ANDROID_INSTALL_STARTUP_SMOKE"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_MOBILE_IOS_PACKAGE_BUILD"
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_NATIVE_TARGET_HOST_RUN_MOBILE_IOS_INSTALL_STARTUP_SMOKE"
contains "scripts/dispatch-native-target-host-workflow.sh" "WORKFLOW_FILE=\"native-target-host.yml\""
contains "scripts/dispatch-native-target-host-workflow.sh" "workflow run \"\$WORKFLOW_FILE\""
contains "scripts/dispatch-native-target-host-workflow.sh" "DEVE_GITHUB_TOKEN"
contains "scripts/dispatch-native-target-host-workflow.sh" "api.github.com/repos"
contains "scripts/dispatch-native-target-host-workflow.sh" "dry-run"
contains "scripts/install-native-target-host-tools.sh" "trunk-rs/trunk/releases/download"
contains "scripts/install-native-target-host-tools.sh" "tauri-apps/tauri/releases/download"
contains "scripts/install-native-target-host-tools.sh" "native-target-host-tools-install: ok"
contains "scripts/build-web-dist-ci.sh" "scripts/smoke-web-release-build.sh"
contains "scripts/build-web-dist-ci.sh" "resolve_tool npm npm.cmd"
contains "scripts/build-web-dist-ci.sh" "resolve_tool trunk trunk.exe"
contains "scripts/build-web-dist-ci.sh" "\"\$npm_bin\" --prefix apps/web ci --ignore-scripts"
contains "scripts/build-web-dist-ci.sh" "\"\$npm_bin\" --prefix apps/web run build"
contains "scripts/build-web-dist-ci.sh" "DEVE_TRUNK_BIN=\"\$trunk_bin\" scripts/smoke-web-release-build.sh"
contains "scripts/smoke-web-release-build.sh" "repo_on_wsl_windows_mount"
contains "scripts/smoke-web-release-build.sh" "web_node_modules_has_windows_esbuild_only"
contains "scripts/smoke-web-release-build.sh" "resolve_windows_trunk_bin"
contains "scripts/collect-native-target-host-evidence.sh" "DEVE_NATIVE_TARGET_HOST_EVIDENCE_COLLECT"
contains "scripts/collect-native-target-host-evidence.sh" "deve-native-target-host-evidence-android"
contains "scripts/collect-native-target-host-evidence.sh" "DEVE_NATIVE_TARGET_HOST_STATUS"
contains "scripts/collect-native-target-host-evidence.sh" "run download"
contains "scripts/collect-native-target-host-evidence.sh" "run list"
contains "scripts/collect-native-target-host-evidence.sh" "run view"
contains "scripts/collect-native-target-host-evidence.sh" "actions/runs"
contains "scripts/collect-native-target-host-evidence.sh" "DEVE_NATIVE_TARGET_HOST_RUN_ID is required; use a run id or latest"
contains "scripts/collect-native-target-host-evidence.sh" "check-native-target-host-evidence.sh"
contains "scripts/collect-native-target-host-evidence.sh" "validate_artifact_name"
contains "scripts/collect-native-target-host-evidence.sh" "prepare_artifact_dir"
contains "scripts/collect-native-target-host-evidence.sh" "invalid artifact name"
contains "scripts/check-native-target-host-evidence.sh" "Process runtime gate: closed"
contains "scripts/check-native-target-host-evidence.sh" "Native authority writes: closed"
contains "scripts/check-native-target-host-evidence.sh" "installer_smoke="
contains "scripts/check-native-target-host-evidence.sh" "invalid_installer_request="
contains "scripts/write-native-target-host-evidence.sh" "Process runtime gate: closed"
contains "scripts/write-native-target-host-evidence.sh" "Native authority writes: closed"
contains "scripts/write-native-target-host-evidence.sh" "Command results:"
contains "scripts/write-native-target-host-evidence.sh" "scripts/check-native-target-host-evidence.sh"
contains "scripts/check-desktop-platform-package-build.sh" "cargo build --release --locked -p deve_cli --bin deve_cli"
contains "scripts/check-desktop-platform-package-build.sh" "\"externalBin\": [\"binaries/deve_cli\"]"
contains "scripts/check-desktop-native-session-package-smoke.sh" "DEVE_DESKTOP_NATIVE_SESSION_SMOKE=1"
contains "scripts/check-desktop-native-session-package-smoke.sh" "DEVE_DESKTOP_LOCAL_SERVICE=1"
contains "scripts/check-desktop-native-session-package-smoke.sh" "desktop-native-session-smoke: ok"
contains "docs/report/native-target-host-evidence-template.md" "# Native Target-host Evidence"
contains "docs/report/native-target-host-evidence-template.md" "Command results:"
contains "docs/report/native-target-host-evidence-template.md" "Artifact paths:"
contains "docs/dev-runbook.md" "scripts/check-native-target-host-evidence.sh"
contains "docs/dev-runbook.md" "scripts/dispatch-native-target-host-workflow.sh"
contains "docs/dev-runbook.md" "scripts/collect-native-target-host-evidence.sh"
contains "docs/dev-runbook.md" "DEVE_NATIVE_TARGET_HOST_STATUS=1"
contains "docs/dev-runbook.md" "DEVE_NATIVE_TARGET_HOST_RUN_ID=latest"
contains "docs/dev-runbook.md" "Platform Artifact Consumption"
contains "docs/dev-runbook.md" "deve-desktop-macos-packages"
contains "docs/dev-runbook.md" "deve-desktop-windows-packages"
contains "docs/dev-runbook.md" "deve-mobile-android-packages"
contains "docs/dev-runbook.md" "deve-mobile-ios-packages"
contains "docs/dev-runbook.md" "shell-only"
contains "docs/dev-runbook.md" "does not claim signed installer readiness"
contains "docs/dev-runbook.md" "scripts/write-native-target-host-evidence.sh"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_STARTUP_SMOKE_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_NATIVE_SESSION_SMOKE_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_INSTALLER_SMOKE_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_NATIVE_TARGET_HOST_RUN_DESKTOP_STARTUP_SMOKE=true"
contains "docs/dev-runbook.md" "DEVE_NATIVE_TARGET_HOST_RUN_DESKTOP_INSTALLER_SMOKE=true"
contains "docs/dev-runbook.md" "DEVE_NATIVE_TARGET_HOST_RUN_MOBILE_IOS_INSTALL_STARTUP_SMOKE=true"

not_contains "Dockerfile" "cargo-chef"
not_contains "Dockerfile" "cargo chef"
not_contains "docs/plan/18_release.md" "cargo-chef"
contains "docs/plan/18_release.md" "固定版本的 Cargo-installed tools（当前为 \`trunk\`）"
contains "docs/plan/18_release.md" "Docker 发布基线 **MUST** 使用 locked direct release build"
contains "Dockerfile" "cargo install trunk --locked --version 0.21.14"
contains "Dockerfile" "rustup target add wasm32-unknown-unknown"
contains "Dockerfile" "https://deb.nodesource.com/setup_24.x"
contains "Dockerfile" "npm ci --ignore-scripts && npm run build"
contains "Dockerfile" "NO_COLOR=true BROWSERSLIST_IGNORE_OLD_DATA=true trunk build --release"
contains "Dockerfile" "COPY --from=frontend /app/apps/web/dist/ /app/apps/web/dist/"
contains "Dockerfile" "cargo build --release --locked --package deve_cli"
contains "Dockerfile" "ENV DEVE_LEDGER_DIR=/data/ledger"
not_contains "Dockerfile" "DEVE_VAULT_PATH"
contains "Dockerfile" "ENV DEVE_BIND_ADDR=0.0.0.0:3001"
contains "Dockerfile" "deve_cli init --repo default --projection-base /notes --path /data"
contains "Dockerfile" "deve_cli serve --port 3001"
assert_before "Dockerfile" "trunk build --release" "cargo build --release --locked --package deve_cli"
assert_before "Dockerfile" "COPY --from=frontend /app/apps/web/dist/ /app/apps/web/dist/" "cargo build --release --locked --package deve_cli"

contains "docker-compose.yml" "AUTH_SECRET: \${AUTH_SECRET:?set AUTH_SECRET to at least 32 random bytes}"
contains "docker-compose.yml" "AUTH_PASS: \${AUTH_PASS:?set AUTH_PASS to an Argon2 PHC password hash}"
contains "docker-compose.yml" "image: ghcr.io/develata/deve-notebook:latest"
contains "docker-compose.yml" "container_name: deve-server"
contains "docker-compose.yml" "restart: always"
contains "docker-compose.yml" "- ./data:/data"
contains "docker-compose.yml" "- ./notes:/notes"
contains "docker-compose.yml" "DEVE_BIND_ADDR: 0.0.0.0:3001"
contains "docker-compose.yml" "DEVE_LEDGER_DIR: /data/ledger"
not_contains "docker-compose.yml" "DEVE_VAULT_PATH"
contains "docker-compose.yml" "mem_limit: 512m"
contains "docker-compose.yml" "http://localhost:3001/api/node/role"
not_contains "docker-compose.yml" "build:"
contains "docker-compose.dev.yml" "build:"
contains "docker-compose.dev.yml" "dockerfile: Dockerfile"
contains "docker-compose.dev.yml" "container_name: deve-server-dev"
contains "docker-compose.dev.yml" "restart: unless-stopped"
contains "docker-compose.dev.yml" "deve-dev-data:/data"
contains "docker-compose.dev.yml" "deve-dev-notes:/notes"
not_contains "docker-compose.dev.yml" "DEVE_VAULT_PATH"
contains "docker-compose.multiclient.yml" "dockerfile: Dockerfile"
contains "docker-compose.multiclient.yml" "\${DEVE_DOCKER_MULTI_PORT:-3101}:3001"
contains "docker-compose.multiclient.yml" "deve-multiclient-data:/data"
contains "docker-compose.multiclient.yml" "deve-multiclient-notes:/notes"
contains "docker-compose.multiclient.yml" "http://localhost:3001/api/node/role"
not_contains "docker-compose.multiclient.yml" "DEVE_VAULT_PATH"
contains "docker-compose.mesh.yml" "dockerfile: Dockerfile"
contains "docker-compose.mesh.yml" "\${DEVE_DOCKER_P2P_MESH_A_PORT:-3111}:3001"
contains "docker-compose.mesh.yml" "\${DEVE_DOCKER_P2P_MESH_B_PORT:-3112}:3001"
contains "docker-compose.mesh.yml" "deve-mesh-peer-a-data:/data"
contains "docker-compose.mesh.yml" "deve-mesh-peer-b-data:/data"
contains "docker-compose.mesh.yml" "DEVE_P2P_ENABLED: \"true\""
contains "docker-compose.mesh.yml" "DEVE_P2P_MESH_PEER_0_AUTH_TOKEN_ENV"
contains "docker-compose.mesh.yml" "DEVE_P2P_INBOUND_TOKEN"
not_contains "docker-compose.mesh.yml" "DEVE_VAULT_PATH"

contains ".env.example" "AUTH_SECRET=replace-with-at-least-32-random-bytes"
contains ".env.example" "AUTH_PASS=\$argon2id\$v=19\$m=65536,t=3,p=1\$..."
contains "docs/plan/18_release.md" "runtime image 只交付单个嵌入前端静态资源的 \`deve_cli\` 二进制"
contains "docs/plan/18_release.md" "delivery shape、environment、ports 与聚合 repo"
contains "docs/plan/18_release.md" "health counts。degraded repo"
contains "docs/plan/18_release.md" "native/graph boundary scripts"
contains "docs/features/15_release.md" "Docker/Server 当前主通道是单个 \`deve_cli\` 二进制"
contains "docs/dev-runbook.md" "DEVE_DOCKER_SMOKE_REQUIRED=1 scripts/smoke-docker-release.sh"
contains "docs/dev-runbook.md" "DEVE_DOCKER_BIN=/path/to/docker"
contains "docs/dev-runbook.md" "http://127.0.0.1:3102/api/node/role"
contains "docs/dev-runbook.md" "DEVE_DOCKER_SMOKE_PORT"
contains "docs/dev-runbook.md" "DEVE_DOCKER_MULTI_REQUIRED=1 bash scripts/smoke-docker-multiclient.sh"
contains "docs/dev-runbook.md" "docker-compose.multiclient.yml"
contains "docs/dev-runbook.md" "DEVE_DOCKER_MULTI_KEEP=1"
contains "docs/dev-runbook.md" "DEVE_DOCKER_P2P_MESH_REQUIRED=1 bash scripts/smoke-docker-p2p-mesh.sh"
contains "docs/dev-runbook.md" "docker-compose.mesh.yml"
contains "docs/dev-runbook.md" "DEVE_DOCKER_P2P_MESH_KEEP=1"
contains "docs/dev-runbook.md" "Native Authority Opt-in"
contains "docs/features/15_release.md" "Docker P2P mesh smoke"
contains "docs/features/15_release.md" "Native authority 只在 explicit opt-in 下可用"
contains "docs/dev-runbook.md" "gh workflow run docker-smoke.yml --ref main"
contains "docs/dev-runbook.md" "It runs the same \`scripts/smoke-docker-release.sh\`"
contains "docs/dev-runbook.md" "scripts/check-native-track-boundary.sh"
contains "docs/dev-runbook.md" "scripts/check-native-packaging-gate.sh"
contains "docs/dev-runbook.md" "scripts/check-native-process-adapter-gate.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-platform-package-preflight.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-android-shell-package-build.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-android-install-startup-smoke.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-android-emulator-install-startup-smoke.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-ios-install-startup-smoke.sh"
contains "docs/dev-runbook.md" "scripts/check-desktop-signing-preflight.sh"
contains "docs/dev-runbook.md" "scripts/check-mobile-android-release-preflight.sh"
contains "docs/dev-runbook.md" "scripts/check-graph-baseline.sh"
contains "docs/acceptance-cases/11_commands_settings.md" "scripts/smoke-web-release-build.sh"
not_contains "docs/features/12_commands.md" "NO_COLOR=true trunk build --release"
not_contains "docs/acceptance-cases/11_commands_settings.md" "NO_COLOR=true trunk build --release"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_SMOKE_REQUIRED"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_SMOKE_PORT:-3102"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_BIN"
contains "scripts/smoke-docker-release.sh" "docker_cmd build -t"
contains "scripts/smoke-docker-release.sh" "docker_cmd run -d"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_SMOKE_DATA_VOLUME"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_SMOKE_NOTES_VOLUME"
contains "scripts/smoke-docker-release.sh" "docker_cmd volume create \"\$DATA_VOLUME\""
contains "scripts/smoke-docker-release.sh" "docker_cmd volume create \"\$NOTES_VOLUME\""
contains "scripts/smoke-docker-release.sh" "docker_cmd volume rm -f \"\$DATA_VOLUME\""
contains "scripts/smoke-docker-release.sh" "docker_cmd volume rm -f \"\$NOTES_VOLUME\""
contains "scripts/smoke-docker-release.sh" "http://127.0.0.1:\${HOST_PORT}/api/node/role"
contains "scripts/smoke-docker-release.sh" "host port \$HOST_PORT already serves /api/node/role"
contains "scripts/smoke-docker-release.sh" "docker_cmd port \"\$CONTAINER_NAME\" 3001/tcp"
contains "scripts/smoke-docker-release.sh" "DEVE_DOCKER_SMOKE_AUTH_PASSWORD"
contains "scripts/smoke-docker-release.sh" "http://127.0.0.1:\${HOST_PORT}/api/auth/login"
contains "scripts/smoke-docker-multiclient.sh" "docker-compose.multiclient.yml"
contains "scripts/smoke-docker-multiclient.sh" "DEVE_DOCKER_MULTI_KEEP"
contains "scripts/smoke-docker-multiclient.sh" "deve-docker-multiclient-playwright"
contains "scripts/smoke-docker-multiclient.sh" "npm --prefix \"\$PLAYWRIGHT_WORK_DIR\" install --no-audit --no-fund \"\$PLAYWRIGHT_PACKAGE\""
contains "scripts/smoke-docker-multiclient.sh" "npm --prefix \"\$PLAYWRIGHT_WORK_DIR\" exec -- playwright install chromium"
contains "scripts/smoke-docker-multiclient.sh" "DEVE_DOCKER_MULTI_PLAYWRIGHT_REQUIRE_FROM=\"\$PLAYWRIGHT_WORK_DIR/package.json\""
contains "scripts/smoke-docker-multiclient.mjs" "await browser.newContext()"
contains "scripts/smoke-docker-multiclient.mjs" "createRequire("
contains "scripts/smoke-docker-multiclient.mjs" "data-deve-search-result-action=\"create-doc\""
contains "scripts/smoke-docker-multiclient.mjs" "context.setOffline(true)"
contains "scripts/smoke-docker-multiclient.mjs" "new URL(url).pathname === \"/ws\""
contains "scripts/smoke-docker-p2p-mesh.sh" "docker-compose.mesh.yml"
contains "scripts/smoke-docker-p2p-mesh.sh" "DEVE_DOCKER_P2P_MESH_REQUIRED"
contains "scripts/smoke-docker-p2p-mesh.sh" "DEVE_DOCKER_P2P_MESH_KEEP"
contains "scripts/smoke-docker-p2p-mesh.sh" "P2P mesh connector handshake completed"
contains "scripts/smoke-docker-p2p-mesh.sh" "P2P token material appeared in compose logs"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-005"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-001"
contains "docs/acceptance-cases/12_tech_release.md" "tags: ['v*']"
contains "docs/acceptance-cases/12_tech_release.md" "type=semver,pattern={{version}}"
contains "docs/acceptance-cases/12_tech_release.md" "type=raw,value=latest"
contains "docs/acceptance-cases/12_tech_release.md" "ghcr.io/\${{ github.repository }}"
not_contains "docs/acceptance-cases/12_tech_release.md" "run: ls dist"
not_contains "docs/acceptance-cases/12_tech_release.md" 'stdout_contains: "v1.0.0"'
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_RELEASE_AUDIT_REQUIRED=1 scripts/check-release-audit-gate.sh"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-006"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-007"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-008"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-009"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-010"
contains "docs/acceptance-cases/12_tech_release.md" "case_id: REL-011"
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_DOCKER_MULTI_REQUIRED=1 bash scripts/smoke-docker-multiclient.sh"
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_DOCKER_P2P_MESH_REQUIRED=1 bash scripts/smoke-docker-p2p-mesh.sh"
contains "docs/acceptance-bindings.tsv" "REL-010|manual-network|docs/dev-runbook.md"
contains "docs/acceptance-bindings.tsv" "REL-011|manual-cli|docs/dev-runbook.md"
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_DOCKER_SMOKE_REQUIRED=1 scripts/smoke-docker-release.sh"
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_DOCKER_BIN=/path/to/docker"
contains "docs/acceptance-cases/12_tech_release.md" "DEVE_RUNTIME_SMOKE_REQUIRED=1 scripts/smoke-runtime-release-info.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/smoke-runtime-happy-path.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/smoke-runtime-recovery-path.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-release-baseline.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-native-track-boundary.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-native-packaging-gate.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-native-process-adapter-gate.sh"
contains "docs/acceptance-cases/12_tech_release.md" "target_host_platform_evidence_shell_only true"
contains "docs/acceptance-cases/12_tech_release.md" "signed_release_readiness_not_claimed true"
contains "docs/acceptance-cases/12_tech_release.md" "store_distribution_readiness_not_claimed true"
contains "docs/acceptance-cases/12_tech_release.md" "physical_device_readiness_not_claimed true"
contains "docs/acceptance-cases/12_tech_release.md" "native_process_runtime_closed true"
contains "docs/acceptance-cases/12_tech_release.md" "native_authority_writes_closed true"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-native-target-host-evidence.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/install-native-target-host-tools.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-package-preflight.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-platform-package-build.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-package-startup-smoke.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-installer-smoke.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-target-host-preflight.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-platform-package-preflight.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-android-shell-package-build.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-android-install-startup-smoke.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-android-emulator-install-startup-smoke.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-ios-install-startup-smoke.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-desktop-signing-preflight.sh"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-mobile-android-release-preflight.sh"
contains "docs/acceptance-cases/12_tech_release.md" "signing_and_physical_device_preflight_diagnostic_only true"
contains "docs/acceptance-cases/12_tech_release.md" "scripts/check-graph-baseline.sh"
contains "docs/dev-runbook.md" "scripts/check-desktop-target-host-preflight.sh"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_TARGET_HOST_PREFLIGHT_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_TARGET_HOSTS=macos"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_TARGET_HOSTS=windows"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_PACKAGE_BUNDLES=app,dmg"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_PACKAGE_NO_SIGN=1"
contains "docs/dev-runbook.md" "cargo tauri build --features native-packaging"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_PACKAGE_BUNDLES=msi,nsis"
contains "docs/dev-runbook.md" "DEVE_MOBILE_PACKAGE_TARGETS=ios"
contains "docs/dev-runbook.md" "DEVE_MOBILE_IOS_PACKAGE_BUILD_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_PACKAGE_DEBUG=1"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_INSTALL_STARTUP_SMOKE_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_APK_PATH=/path/to/signed.apk"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_SERIAL=<adb-serial>"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_ADB_TIMEOUT_SECS"
contains "docs/dev-runbook.md" "skips host Linux"
contains "docs/dev-runbook.md" "native-packaging cargo checks"
contains "docs/dev-runbook.md" "DEVE_MOBILE_IOS_INSTALL_STARTUP_SMOKE_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_DESKTOP_SIGNING_PREFLIGHT_REQUIRED=1"
contains "docs/dev-runbook.md" "APPLE_SIGNING_IDENTITY"
contains "docs/dev-runbook.md" "WINDOWS_SIGNING_CERT_BASE64"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_RELEASE_PREFLIGHT_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_MOBILE_ANDROID_PHYSICAL_DEVICE_PREFLIGHT_REQUIRED=1"
contains "docs/dev-runbook.md" "DEVE_ANDROID_KEYSTORE_BASE64"
contains "docs/dev-runbook.md" "no-process/no-authority boundary"
contains "docs/dev-runbook.md" "native-target-host-evidence-template.md"
contains "docs/dev-runbook.md" "deve-native-target-host-evidence-"
contains "docs/report/native-target-host-handoff-2026-05-14.md" "Native Target-host Handoff"
contains "docs/report/native-target-host-handoff-2026-05-14.md" "Desktop macOS"
contains "docs/report/native-target-host-handoff-2026-05-14.md" "Desktop Windows"
contains "docs/report/native-target-host-handoff-2026-05-14.md" "Mobile iOS"
contains "docs/report/native-target-host-handoff-2026-05-14.md" "Process runtime gate remains closed"
contains "scripts/check-desktop-target-host-preflight.sh" "DEVE_DESKTOP_TARGET_HOST_PREFLIGHT_REQUIRED"
contains "scripts/check-desktop-target-host-preflight.sh" "DEVE_DESKTOP_TARGET_HOSTS"
contains "scripts/check-desktop-target-host-preflight.sh" "DEVE_DESKTOP_PACKAGE_NO_SIGN"
contains "scripts/check-desktop-target-host-preflight.sh" "macOS target-host requires Darwin"
contains "scripts/check-desktop-target-host-preflight.sh" "Windows target-host requires Windows"
contains "scripts/check-desktop-target-host-preflight.sh" "APPLE_SIGNING_IDENTITY"
contains "scripts/check-desktop-target-host-preflight.sh" "APPLE_PROVIDER_SHORT_NAME"
contains "scripts/check-desktop-target-host-preflight.sh" "Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
contains "scripts/check-desktop-target-host-preflight.sh" "WiX Toolset"
contains "scripts/check-desktop-target-host-preflight.sh" "NSIS makensis"
contains "scripts/check-mobile-platform-package-preflight.sh" "DEVE_MOBILE_PACKAGE_PREFLIGHT_REQUIRED"
contains "scripts/check-mobile-platform-package-preflight.sh" "DEVE_MOBILE_PACKAGE_TARGETS"
contains "scripts/check-mobile-platform-package-preflight.sh" "DEVE_MOBILE_ANDROID_PACKAGE_TARGET"
contains "scripts/check-mobile-platform-package-preflight.sh" "DEVE_MOBILE_PACKAGE_HOST_NATIVE_PACKAGING_CHECK"
contains "scripts/check-mobile-platform-package-preflight.sh" "x86_64-linux-android"
contains "scripts/check-mobile-platform-package-preflight.sh" "cargo tauri android --help"
contains "scripts/check-mobile-platform-package-preflight.sh" "cargo tauri ios --help"
contains "scripts/check-mobile-platform-package-preflight.sh" "Android shell package build is allowed only through scripts/check-mobile-android-shell-package-build.sh"
contains "scripts/check-mobile-android-shell-package-build.sh" "DEVE_MOBILE_ANDROID_PACKAGE_BUILD_REQUIRED"
contains "scripts/check-mobile-android-shell-package-build.sh" "DEVE_MOBILE_ANDROID_PACKAGE_DEBUG"
contains "scripts/check-mobile-android-shell-package-build.sh" "--debug"
contains "scripts/check-mobile-android-shell-package-build.sh" "cargo tauri android init --ci --skip-targets-install"
contains "scripts/check-mobile-android-shell-package-build.sh" "cargo tauri android build --ci --features native-packaging"
contains "scripts/check-mobile-android-shell-package-build.sh" "child-process runtime"
contains "scripts/check-mobile-ios-shell-package-build.sh" "DEVE_MOBILE_IOS_PACKAGE_BUILD_REQUIRED"
contains "scripts/check-mobile-ios-shell-package-build.sh" "DEVE_MOBILE_IOS_PACKAGE_TARGET:-aarch64-sim"
contains "scripts/check-mobile-ios-shell-package-build.sh" "cargo tauri ios init --ci --skip-targets-install"
contains "scripts/check-mobile-ios-shell-package-build.sh" "cargo tauri ios build --ci --features native-packaging"
contains "scripts/check-mobile-ios-shell-package-build.sh" "child-process runtime"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_INSTALL_STARTUP_SMOKE_REQUIRED"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_SERIAL"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_ADB_TIMEOUT_SECS"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "app-universal-debug.apk"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "adb_timed install -r"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "android.intent.category.LAUNCHER"
contains "scripts/check-mobile-android-install-startup-smoke.sh" "child-process runtime"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_EMULATOR_INSTALL_STARTUP_SMOKE_REQUIRED"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_EMULATOR_SYSTEM_TARGET:-default"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "print_emulator_diagnostics"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "ANDROID_AVD_HOME"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "avdmanager.log"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "sdkmanager"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "avdmanager"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "emulator"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "DEVE_MOBILE_ANDROID_PACKAGE_DEBUG=1"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "check-mobile-android-shell-package-build.sh"
contains "scripts/check-mobile-android-emulator-install-startup-smoke.sh" "check-mobile-android-install-startup-smoke.sh"
contains "scripts/check-mobile-ios-install-startup-smoke.sh" "DEVE_MOBILE_IOS_INSTALL_STARTUP_SMOKE_REQUIRED"
contains "scripts/check-mobile-ios-install-startup-smoke.sh" "DEVE_MOBILE_IOS_BOOT_SIMULATOR"
contains "scripts/check-mobile-ios-install-startup-smoke.sh" "xcrun_cmd simctl install"
contains "scripts/check-mobile-ios-install-startup-smoke.sh" "xcrun_cmd simctl launch"
contains "scripts/check-mobile-ios-install-startup-smoke.sh" "child-process runtime"
contains "scripts/check-desktop-signing-preflight.sh" "DEVE_DESKTOP_SIGNING_PREFLIGHT_REQUIRED"
contains "scripts/check-desktop-signing-preflight.sh" "DEVE_DESKTOP_SIGNING_TARGETS"
contains "scripts/check-desktop-signing-preflight.sh" "APPLE_PROVIDER_SHORT_NAME"
contains "scripts/check-desktop-signing-preflight.sh" "WINDOWS_SIGNING_CERT_BASE64"
contains "scripts/check-desktop-signing-preflight.sh" "signing/notarization not executed"
contains "scripts/check-mobile-android-release-preflight.sh" "DEVE_MOBILE_ANDROID_RELEASE_PREFLIGHT_REQUIRED"
contains "scripts/check-mobile-android-release-preflight.sh" "DEVE_MOBILE_ANDROID_PHYSICAL_DEVICE_PREFLIGHT_REQUIRED"
contains "scripts/check-mobile-android-release-preflight.sh" "DEVE_ANDROID_KEYSTORE_BASE64"
contains "scripts/check-mobile-android-release-preflight.sh" "physical Android device"
contains "scripts/check-mobile-android-release-preflight.sh" "signed release and physical-device smoke not executed"
contains "scripts/check-native-process-adapter-gate.sh" "DeferredUntilPackagingGate"
contains "scripts/check-native-process-adapter-gate.sh" "check_no_process_runtime_leak"
contains "scripts/check-native-process-adapter-gate.sh" "DEVE_NATIVE_PROCESS_ADAPTER_RUN_DESKTOP_NATIVE_PACKAGING_TESTS"
contains "scripts/check-native-process-adapter-gate.sh" "process_observation"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Decision: \`KeepClosedUntilExplicitRuntimeFeature\`"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "No real child-process runtime was opened."
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Desktop macOS"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Desktop Windows"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Android shell APK package execution is closed"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "iOS simulator shell package build is closed"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Mobile process runtime must wait for Android/iOS install/startup evidence"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "Command::new"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "tokio::process"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "direct spawn"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "must be a separate implementation batch"
contains "docs/report/process-runtime-gate-decision-after-target-host-closure-2026-05-15.md" "current implementation policy name"
contains "docs/report/mobile-install-startup-evidence-plan-2026-05-15.md" "Mobile install/startup has executable fail-closed gates"
contains "docs/report/mobile-install-startup-evidence-plan-2026-05-15.md" "scripts/check-mobile-android-emulator-install-startup-smoke.sh"
contains "docs/report/mobile-install-startup-evidence-plan-2026-05-15.md" "Android emulator/device"
contains "docs/report/mobile-install-startup-evidence-plan-2026-05-15.md" "booted iOS simulator"
contains "docs/plan/11_ui_design/03_mobile.md" "{#mobile-android-shell-package-execution-gate}"
contains "docs/plan/11_ui_design/03_mobile.md" "{#mobile-ios-shell-package-execution-gate}"
contains "docs/plan/11_ui_design/03_mobile.md" "Android package build **MUST NOT** 启动、持有、重启后端子进程"
contains "docs/plan/11_ui_design/03_mobile.md" "iOS package build **MUST NOT** 启动、持有、重启后端子进程"
contains "docs/report/mobile-android-shell-package-gate-2026-05-14.md" "Android shell-only package execution"
contains "docs/acceptance-cases/12_tech_release.md" 'json_fields_present: ["version", "profile", "delivery", "environment"]'
contains "docs/acceptance-cases/12_tech_release.md" 'json_fields_present: ["repo_health.status", "repo_health.local_total", "repo_health.degraded"]'
contains "docs/features/15_release.md" "版本、profile、环境、交付形态和 repo health 聚合状态"
contains "docs/dev-runbook.md" "repo_health.status=degraded"
contains "apps/cli/src/server/node_role_http.rs" '"version": r.version'
contains "apps/cli/src/server/node_role_http.rs" '"profile": r.profile'
contains "apps/cli/src/server/node_role_http.rs" '"delivery": r.delivery'
contains "apps/cli/src/server/node_role_http.rs" '"environment": r.environment'
contains "apps/cli/src/server/node_role_http.rs" '"repo_health":'
contains "apps/cli/src/server/node_role.rs" "from_degraded_count_clamps_degraded_count_to_local_total"
contains "apps/cli/src/server/start.rs" "repo_health_summary"
contains "apps/cli/src/server/static_files.rs" '"embedded-frontend"'
contains "apps/web/src/api/connection_role.rs" "format_node_role_summary"
contains "apps/web/src/api/connection_role.rs" "format_repo_health"
contains "apps/web/src/components/dashboard/runtime_card.rs" "RuntimeCard"
contains "apps/web/src/components/settings.rs" 'env!("CARGO_PKG_VERSION")'
contains "apps/web/src/main.rs" "Web app mount skipped"
not_contains "apps/web/src/main.rs" "web_sys::window().unwrap()"
not_contains "apps/web/src/main.rs" "window.document().unwrap()"
contains "scripts/smoke-runtime-release-info.sh" "/api/node/role"
contains "scripts/smoke-runtime-release-info.sh" "DEVE_RUNTIME_SMOKE_REQUIRED"
contains "scripts/smoke-runtime-release-info.sh" "allowed_delivery"
contains "scripts/smoke-runtime-release-info.sh" "repo_health"
contains "scripts/smoke-runtime-release-info.sh" "repo_health counts do not add up"
contains "scripts/smoke-runtime-release-info.sh" "unknown repo_health must use zero counts"
contains "scripts/smoke-runtime-happy-path.sh" "ws_endpoint_sync_hello_uses_switched_repo_scope"
contains "scripts/smoke-runtime-happy-path.sh" "ws_endpoint_register_writer_after_sync_hello_returns_write_ready"
contains "scripts/smoke-runtime-happy-path.sh" "ws_edit_after_register_writer_emits_new_op_and_ack"
contains "scripts/smoke-runtime-happy-path.sh" "ws_open_doc_and_history_read_back_registered_edit"
contains "scripts/smoke-runtime-happy-path.sh" "restore_runs_only_on_clean_reconnect_edge"
contains "scripts/smoke-runtime-happy-path.sh" "expected exactly one executed test"
contains "scripts/smoke-runtime-happy-path.sh" "expected passing test"
contains "scripts/smoke-runtime-recovery-path.sh" "degraded_local"
contains "scripts/smoke-runtime-recovery-path.sh" "sync_scope_cleanup"
contains "scripts/smoke-runtime-recovery-path.sh" "write_gate"
contains "scripts/smoke-runtime-recovery-path.sh" "message_refresh"
contains "scripts/smoke-runtime-recovery-path.sh" "status_summary"
contains "scripts/smoke-runtime-recovery-path.sh" "auth_probe"
contains "scripts/smoke-runtime-recovery-path.sh" "expected at least one test"
contains "scripts/check-release-audit-gate.sh" "cargo audit"
contains "scripts/check-release-audit-gate.sh" "npm --prefix"
contains "scripts/check-release-audit-gate.sh" "DEVE_RELEASE_AUDIT_REQUIRED"
contains "scripts/check-release-audit-gate.sh" "skip cargo audit"
contains "docs/features/operations/release_quality_gates.md" "runtime happy-path and recovery smokes remain explicit local/CI script gates"

echo "release-baseline-check: ok"
