[package]
name = "deve_desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
native-packaging = []

[dependencies]
deve_core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
